{
 "title": "Mesh",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   {
    "name": "namespace",
    "query": "label_values(http_requests_total, backend)"
   },
   {
    "name": "backend",
    "query": "label_values(http_requests_total{backend=~\"$namespace.*\"}, backend)"
   }
  ]
 },
 "panels": [
  {
   "title": "Success rate (non 500 HTTP)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status_code!~\"5.*\", backend=~\"$namespace-$backend.*\"}[1m])) by (backend) / sum(rate(http_requests_total{backend=~\"$namespace-$backend.*\"}[1m])) by (backend)) < 1",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "4XX HTTP rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(http_requests_total{status_code=~\"4.*\", backend=~\"$namespace-$backend.*\"}[1m])) by (backend, status_code)",
     "legendFormat": "{{backend}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "5XX HTTP rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(http_requests_total{status_code=~\"5.*\", backend=~\"$namespace-$backend.*\"}[1m])) by (backend, status_code)",
     "legendFormat": "{{backend}} - {{status_code}}"
    }
   ]
  },
  {
   "title": "RPS per workload",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=\"200\", backend=~\"$namespace-$backend.*\"}[1m])) by (backend)",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "Slow queries 0.99 (more than 1s)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(irate(http_request_duration_seconds_bucket{backend=~\"$namespace-$backend.*\"}[1m])) by (le, backend)) > 1",
     "legendFormat": "{{backend}}"
    }
   ]
  },
  {
   "title": "AVG time per URL Q=0.99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, avg(irate(http_request_duration_seconds_bucket{backend=~\"$namespace-$backend.*\"}[1m])) by (le, backend, url))",
     "legendFormat": "{{url}} - {{backend}}"
    }
   ]
  }
 ]
}