---
kind: Service
apiVersion: v1
metadata:
  name: haproxy-ingress-controller-fluentd-metrics
  namespace: default
  labels:
    app: haproxy-ingress
    release: ha-ingress
    type: metrics
  # annotations:
  #   prometheus.io/port: '9101'
  #   prometheus.io/scrape: 'true'
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 24231
      targetPort: 24231
  selector:
    app: haproxy-ingress
    component: controller
    release: ha-ingress
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ha-ingress
  name: ha-ingress-stats
  namespace: prometheus
spec:
  endpoints:
  - interval: 15s
    port: metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: haproxy-ingress
      type: metrics
